CREATE TABLE EXPENSES (
    EXPENSE_ID UUID PRIMARY KEY,
    ITEM VARCHAR (100) NOT NULL,
    AMOUNT DECIMAL (10, 2) NOT NULL,
    EXPENSE_DATE DATE NOT NULL,
    NOTES VARCHAR (255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- TODO LATER
-- CREATE TABLE CATEGORIES (
--     CATEGORY_ID UUID PRIMARY KEY,
--     NAME VARCHAR (100) NOT NULL UNIQUE
-- );
--
-- CREATE TABLE EXPENSES (
--     EXPENSE_ID UUID PRIMARY KEY,
--     CATEGORY_ID UUID,
--     ITEM VARCHAR (100) NOT NULL,
--     AMOUNT DECIMAL (10, 2) NOT NULL,
--     EXPENSE_DATE DATE NOT NULL,
--     NOTES VARCHAR (255),
--     CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (CATEGORY_ID)
-- );